"""empty message

Revision ID: 0e05560a62d0
Revises: 94c664ee0adc
Create Date: 2022-09-27 00:45:36.260029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e05560a62d0'
down_revision = '94c664ee0adc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
