"""03

Revision ID: 1adc04a38be1
Revises: 814735340551
Create Date: 2022-08-23 17:27:06.084543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1adc04a38be1'
down_revision = '814735340551'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'theme', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'theme', type_='unique')
    # ### end Alembic commands ###
