"""add user model

Revision ID: ac44e49628aa
Revises: 1adc04a38be1
Create Date: 2022-09-24 22:08:33.098496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac44e49628aa'
down_revision = '1adc04a38be1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
